---
title: "Simple document"
output: github_document
---


I'm an R Markdown document! 

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r, echo= FALSE, message=FALSE}
library(tidyverse)
```

## Import some data

I want to import `FAS_litters.csv`
```{r}
litters_df=read_csv("FAS_litters.csv")
```
```{r}
names(litters_df)
litters_df=janitor:: clean_names(litters_df)
```
```{r}
litters_df
head(litters_df)
```

#Arguments in `read.csv`
```{r}
litters_data = read_csv(file = "./FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```
  
```{r}
library(tidyverse)
```
```{r}
mlb11_df= readxl::read_excel("mlb11.xlsx")
```
#Read a SAS file
```{r}
library(haven)
```
```{r}
pulse_df=read_sas("public_pulse_data.sas7bdat")
```